import Head from 'next/head';
import { useEffect } from 'react';
import * as zoomApi from '../apis/index';

export default function Home() {
	const getSample = async () => {
		const data = await zoomApi.default.getReport('2023', '03');
		console.log('data,', data);
	};

	useEffect(() => {
		getSample();
	}, []);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</>
	);
}
